# Creeper has no sell price as it's function is to give TNT.

collector-item:
  name: "&b&lCollector"
  lore:
    - "&7Automatically collect certain drops in a chunk."

collection-types:
  CACTUS:
    name: "&eCactus"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: CACTUS
    durability: 0
    gui-slot: 12
    sell-price: 1.0
  SUGAR_CANE:
    name: "&eSugarcane"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: MONSTER_EGG
    durability: 50
    gui-slot: 13
    sell-price: 12.5
  CREEPER:
    name: "&eTNT"
    lore:
      - "&7You currently have &e%amount% &7available to withdraw."
    material: MONSTER_EGG
    durability: 50
    gui-slot: 14
  PIG:
    name: "&ePig"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: DIAMOND_SWORD
    durability: 0
    gui-slot: 21
    sell-price: 0.5
  COW:
    name: "&eCow"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: DIAMOND_SWORD
    durability: 0
    gui-slot: 22
    sell-price: 3.0
  PIG_ZOMBIE:
    name: "&eZombie Pigmen"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: DIAMOND_SWORD
    durability: 0
    gui-slot: 23
    sell-price: 13.5
  ENDERMAN:
    name: "&eEndermen"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: DIAMOND_SWORD
    durability: 0
    gui-slot: 30
    sell-price: 11.0
  IRON_GOLEM:
    name: "&eIron Golem"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: DIAMOND_SWORD
    durability: 0
    gui-slot: 31
    sell-price: 75.0
  VILLAGER:
    name: "&eVillager"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: DIAMOND_SWORD
    durability: 0
    gui-slot: 32
    sell-price: 35.0