# Creeper has no sell price as it's function is to give TNT.

gui-size: 45

collector-item:
  name: "&b&lCollector"
  lore:
    - "&7Automatically collect certain drops in a chunk."

info-item:
  name: "&b&lINFO"
  lore:
    - "&7Collectors allow you to easily collect and sell"
    - "&7a range of drops."
  material: BOOK
  durability: 0

collection-types:
  CREEPER:
    name: "&eTNT"
    lore:
      - "&7You currently have &e%amount% &7available to withdraw."
    material: TNT
    durability: 0
    gui-slot: 29

  ZOMBIE:
    name: "&eZombie"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: MONSTER_EGG
    durability: 54
    gui-slot: 15
    sell-price: 1.1
  SKELETON:
    name: "&eSkeleton"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: MONSTER_EGG
    durability: 51
    gui-slot: 21
    sell-price: 1.1

  PIG_ZOMBIE:
    name: "&eZombie Pigmen"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: MONSTER_EGG
    durability: 57
    gui-slot: 30
    sell-price: 9.9
  BLAZE:
    name: "&eBlaze"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: MONSTER_EGG
    durability: 61
    gui-slot: 30
    sell-price: 16.5
  IRON_GOLEM:
    name: "&eIron Golem"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: MONSTER_EGG
    durability: 91
    gui-slot: 33
    sell-price: 18.7
  VILLAGER:
    name: "&eVillager"
    lore:
      - "&7You currently have &e%amount% &7available to sell."
    material: MONSTER_EGG
    durability: 120
    gui-slot: 31
    sell-price: 77.0
