name: Collectors
author: ufo
version: ${project.version}
main: me.ufo.collectors.CollectorsPlugin
description: ${project.description}
depend: [Vault, WorldGuard, Factions]
commands:
  collectors:
    aliases: [collector]